### ISSUE TITLE
Add template definition for mapper and reducer

### ISSUE THREAD

**Issue by AALEKH** [STEllAR-GROUP/hpxflow#23]
This issue is meant to solve: https://gist.github.com/AALEKH/04ee46f71cd3a2410760b50ced61612d

**Comment by hkaiser** [comment]
You probably meant to add a _definition_ of the template. The declaration is already in place as otherwise the code wouldn't compile (as opposed to the current situation, where it does not link).

**Comment by AALEKH** [comment]
@hkaiser Yup, updated title accordingly
